source "https://github.com/CocoaPods/Specs.git"
platform :ios, '9.0'

target 'RNFaceVerify' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'TencentCloudHuiyanSDKFace_framework', :path => './TencentCloudHuiyanSDKFace_framework'
  pod 'TencentCloudHuiyanSDKWill_framework', :path => './TencentCloudHuiyanSDKWill_framework'
end
